name: catty-reminders

services:
  db:
    image: mariadb:11
    container_name: catty-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: mypass
      MARIADB_DATABASE: catty_reminders
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: ghcr.io/quangminh-202/devops-minh:latest
    container_name: catty-app
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      SECRET_KEY: "Cats are awesome!"
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: catuser
      DB_PASSWORD: catpass
      DB_NAME: catty_reminders

volumes:
  db-data: