name: CI - Run All Tests

on:
  push:
    branches:
      - main
      - docker
      - github-action
      - docker-compose
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd catty-reminders-app 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-playwright fastapi uvicorn jinja2

      - name: Install browsers (for UI tests)
        run: |
          python -m playwright install chromium
      
      - name: Start FastAPI app      
        run: |      
          cd catty-reminders-app      
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8181 &      
          sleep 5  
      
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}} 
          tags: |
            type=raw, value=latest
            type=ref, event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: True
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
